export const GET_PROJECTS = 'App/GET_PROJECTS';
export const SET_PROJECTS = 'App/SET_PROJECTS';
export const UPDATE_PROJECT = 'App/UPDATE_PROJECT';
export const UPDATE_PROJECT_PROGRESS = 'App/UPDATE_PROJECT_PROGRESS';
